using Content.Shared.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class CargoOrderTrackerUiFragment : BoxContainer
{
    public CargoOrderTrackerUiFragment()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(Dictionary<string, CargoOrderTrackerData> cargoOrders)
    {
        TrackedOrdersContainer.RemoveAllChildren();
    }
}
