using Content.Shared.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class CargoOrderTrackerUiFragment : BoxContainer
{
    public event Action<int>? OnOrderAdded;
    public event Action<int>? OnOrderRemoved;
    public CargoOrderTrackerUiFragment()
    {
        RobustXamlLoader.Load(this);

        Input.OnTextEntered += _ =>
        {
            Input.Clear();
        };
    }

    public void UpdateState(Dictionary<int, CargoOrderTrackerData> cargoOrders)
    {
        TrackedOrdersContainer.RemoveAllChildren();
    }
}
